In [2]:
#matrix multiplication using NumPy

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dot(a,b)

print(c)


[[19 22]
 [43 50]]


In [3]:
# stack two arrays vertically using NumPy
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a,b))

print(c)


[[1 2 3]
 [4 5 6]]


In [4]:
#generate a custom sequence using NumPy

import numpy as np

a = np.arange(0, 10, 2)

print(a)


[0 2 4 6 8]


In [5]:
#arithmetic operations on NumPy arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

print(c)


[5 7 9]


In [6]:
# bitwise operations on NumPy arrays
import numpy as np

a = np.array([1, 2], dtype=np.uint8)
b = np.array([4, 5], dtype=np.uint8)

c = np.bitwise_and(a,b)

print(c)


[0 0]


In [7]:
# stack two arrays horizontally using NumPy:
import numpy as np

a = np.array([1, 2], dtype=np.uint8)

b = a.copy()

c = a.view()

print(b)
print(c)


[1 2]
[1 2]


In [8]:
#search for elements in a NumPy array
import numpy as np

a = np.array([1, 2])

b = (a == 2)

print(b)


[False  True]


In [9]:
#count elements in a NumPy array
import numpy as np

a = np.array([3, 1, 2])


b = np.sort(a)

print(b)


[1 2 3]


In [10]:
#broadcast elements in a NumPy array
import numpy as np

a = np.array([[1], [2]])
b = np.array([3])

c = a + b

print(c)


[[4]
 [5]]
